services:
    auth:
      build: .
      ports:
        - "8000:8000"
      depends_on:
        - postgres
        - redis
      environment:
        - POSTGRES_HOST=${POSTGRES_HOST}
        - REDIS_HOST=${REDIS_HOST}
        - REDIS_DB=${REDIS_DB}

    postgres:
      image: postgres:16
      environment:
        - POSTGRES_DB=${POSTGRES_DB}
        - POSTGRES_USER=${POSTGRES_USER}
        - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      ports:
        - "5432:5432"

    redis:
      image: redis:6.2.6
      ports:
        - "6379:6379"